allowBuilds:
  '@sveltejs/kit': true
  esbuild: true
  protobufjs: true
  sharp: true
  svelte-preprocess: true
onlyBuiltDependencies:
  - '@sveltejs/kit'
  - esbuild
  - protobufjs
  - sharp
  - svelte-preprocess
